routes/web.php
<?php

use Illuminate\Http\Request;
Route::get('/', function () {
    return view('landingpage');
});

Auth::routes();

Route::get('/home', 'PagesController@index')->name('home');

Route::get('/about', 'HomeController@about')->name('about');

Route::get('/about', 'PagesController@about')->name('about');

Route::get('/payment', 'PagesController@payment')->name('paymentform');

Route::post('/submit', 'Formcontroller@submit')->name('paymentform');



Route::get('/terms_and_condition', function () {
	    return view('landingpage');
});

Route::get('/terms_and_condition_washer', function () {
	    return view('landingpage');
});

Route::get('/code_of_conduct', function () {
	    return view('landingpage');
});

Route::get('/privacy_policy', function () {
	    return view('privacy');
});


Route::get('/paymentgateway', 'StripePaymentGatewayController@makepayment');
Route::get('/stripesuccess', 'StripePaymentGatewayController@stripesuccess');
Route::get('/stripefail', 'StripePaymentGatewayController@stripefail');



Route::group(['prefix' => 'admin', 'middleware' => ['admin']], function() {
	Route::get('complains', 'AdminController@complain');
	Route::get('/washer/{id}', 'WasherController@viewwasherdetails');
	Route::get('/activatewasher/{id}', 'WasherController@approvewasherdetails');
	Route::resource('seo', 'SeoController');
	Route::get('requests', 'AdminController@request');
	Route::get('callbacks', 'AdminController@callback');
	Route::get('ondemand', 'AdminController@ondemand');
	Route::get('contacts', 'AdminController@contact');
	Route::get('services','AdminController@service');
	Route::get('slider_images','AdminController@slider_image');
	Route::get('userlists','AdminController@userlist');
	Route::get('washerlists','AdminController@washerlist');
	Route::get('book_car_wash','AdminController@showcarwashbookingform');
	Route::post('book_car_wash','AdminController@savecarwashrequest');


	Route::get('complain_destroy', 'AdminController@complain_destroy');
	Route::get('home', 'AdminController@showhome');
	Route::resource('slider_img', 'SliderController');
	Route::resource('services', 'ServiceController');
	Route::resource('faqs', 'FAQController');
	Route::resource('car_wash', 'CarwashController');
	// Route::resource('car_service', 'CarservicingController');
	Route::resource('cars', 'CarController');
	Route::resource('feedbacks', 'FeedbackController');
	Route::resource('accessories', 'CaraccessoriesController');
	Route::resource('brands', 'BrandController');
	Route::resource('carmodels', 'ModelController');
	Route::get('getmodel/{brand_id}', 'AdminController@model_data');
	// Route::get('template', 'AdminController@template');
	Route::get('users', 'AdminController@showusers');
	Route::get('sendsms', 'AdminController@showsendsms');
	Route::get('pendingorder', 'AdminController@pendingorder');
	Route::resource('promocode', 'PromoCodeAdminController');
	Route::post('sendsms', 'AdminController@sendsms');
	// Route::get('vehicle_types', 'AdminController@showvehiclelist');
	// Route::resource('vehicle_types', 'VehicleAdminController');
	// Route::resource('couponcode', 'CouponAdminController');

});



// for Terms & condition
Route::get('tnc', 'TermController@showtnc');
// for Privacy
Route::get('privacy', 'TermController@showprivacy');

Route::get('addmoney/stripe', array('as' => 'addmoney.paywithstripe','uses' => 'AddMoneyController@payWithStripe'));
Route::post('addmoney/stripe', array('as' => 'addmoney.stripe','uses' => 'AddMoneyController@postPaymentWithStripe'));
Route::get ( '/redirect/{service}', 'SocialLoginController@redirectToProvider' );
Route::get ( '/callback/{service}', 'SocialLoginController@callback' );

app/AccountSetting.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class AccountSetting extends Model
{
    //
}

app/Bank.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Bank extends Model
{
    //
}

app/Brand.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Brand extends Model
{
    protected $fillable = [
        'brand_name', 'description', 'brand_img','status'
    ];
}

app/Car.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Car extends Model
{
    protected $fillable=[
    	'car_category','brand_id','car_model','car_img','car_desc','status'
    ];
}

app/Carmodel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Carmodel extends Model
{
    //
}

app/Complaint.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Complaint extends Model
{
    //
}

app/FAQ.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class FAQ extends Model
{
    //
}

app/MyCar.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class MyCar extends Model
{
    //
}

app/MyReward.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class MyReward extends Model
{
    //
}

app/Notifications.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Notifications extends Model
{
    //
}

app/OTP.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class OTP extends Model
{
    //
}

app/PaymentCard.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class PaymentCard extends Model
{
    //
}

app/Profile.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Profile extends Model
{
    //
}

app/PromoCode.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class PromoCode extends Model
{
    //
}

app/Redeem.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Redeem extends Model
{
    //
}

app/Reward.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Reward extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Tymon\JWTAuth\Contracts\JWTSubject;


class User extends Authenticatable implements JWTSubject
{
    use Notifiable;
    

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'user_type', 'mobile', 'device_token', 'provider_id', 'provider'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function getJWTIdentifier()
    {
        return $this->getKey();
    }

    public function getJWTCustomClaims()
    {
        return [];
    }
}

app/UserReward.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class UserReward extends Model
{
    //
}

app/Wallet.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Wallet extends Model
{
    protected $table = 'wallet_money_add';
    protected $hidden = ['created_at', 'updated_at'];
}

app/WasherDetails.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class WasherDetails extends Model
{
    //
}

resources/views/admin/accessories.blade.php
@extends('layouts.admin')


@section('content')
<h4 class="header-title m-t-0 m-b-30">Default Example</h4>
<h4 class="header-title m-t-0 m-b-30">Accessories List <a href="{{ url('admin/accessories/create')}}" class="btn btn-primary btn-xs">Add Accessory</a></h4>
@if(Session::has('message'))
   <div class="alert alert-success">{{ Session::get('message') }}</div>
@endif
<table id="datatable" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Image</th>
            <th>Description</th>
            <th>Action</th>
        </tr>
    </thead>

    <tbody>
        <?php $i=1; ?>
        <?php var_dump($accessories); die;?>
        	@foreach ($accessories as $accessory)
            <tr>
                <td> {{ $i }}</td>
                <td>{{ $accessory->name }}</td>
                <td>
                   {{--  <?php 
                        $data[] = $saccessory->image[]; 
                    ?> 
                    @foreach()
                    <img src="{{ asset('images/accessories/'.$accessory->image) }}" alt="" style="width: 100px; height: 50px;"> --}}

                </td>
                <td>{{ $accessory->description }}</td>
                <td>
                    {{ link_to_route('accessories.edit','Edit',[$accessory->id], ['class'=> 'btn btn-primary btn-xs col-md-2']) }}

                        {!! Form::open(['method'=>'delete','route'=>['accessories.destroy', $accessory->id],'class'=>'col-md-6' ]) !!}

                    {!! Form::submit('Delete',['class'=>'btn btn-danger btn-xs' ])!!}
               </td>
            </tr>
            <?php $i++; ?> 
            @endforeach
        @endif
       
    </tbody>
</table>                    
@endsection

resources/views/admin/add_accessory.blade.php
@extends('layouts.admin')


@section('content')
<h4 class="header-title m-t-0 m-b-30">Default Example</h4>
<h4 class="header-title m-t-0 m-b-30">Add Accessory</h4>
@if(isset($success))
    <div class="alert alert-success"> {{$success}} </div>
@endif
@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
@if(isset($accessories))
    {{ Form::model($accessories, ['route' => ['accessories.update', $accessories->id],'class'=>'form-horizontal', 'files' => true, 'method' => 'patch']) }}
@else

    {!!  Form::open(array('route' =>'accessories.store','class'=>'form-horizontal','files' => true )) !!}

@endif
                                        
                                        
                <div class="form-group">
                    {!! Form::label('title','Name :',['class'=>'col-sm-3 control-label'])!!}
                    <div class="col-sm-6">
                        {!! Form::text('name',Input::old('name'),['class'=>'form-control'])!!}
                    </div>
                </div>
                <div class="form-group">
                    {!! Form::label('title','Description :',['class'=>'col-sm-3 control-label'])!!}
                    <div class="col-sm-6">
                        {!! Form::text('description',Input::old('description'),['class'=>'form-control'])!!}
                    </div>
                </div>
                
                <div class="form-group">
                    {!! Form::label('title','Image :',['class'=>'col-sm-3 control-label'])!!}
                    <div class="col-sm-6">
                        {!! Form::file('image[]',['class'=>'form-control','multiple'],Input::old('image')) !!}
                    </div>
                </div>	
               
                <div class="form-group">
                    <div class="col-sm-6 col-sm-offset-5">
                        {!! Form::submit('submit',array('class' => 'btn btn-primary'))!!}
                    </div>
                </div>


            {!! Form::close() !!}                  
                                         


                        

                    
@endsection

resources/views/admin/add_booking.blade.php
@extends('layouts.admin')


@section('content')
<h4 class="header-title m-t-0 m-b-30">Default Example</h4>
<h4 class="header-title m-t-0 m-b-30">Add Car Wash Booking </h4>
@if(isset($success))
    <div class="alert alert-success"> {{$success}} </div>
@endif
@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif     

       {{-- @if(isset($car_wash))
    {{ Form::model($car_wash, ['route' => ['car_wash.update', $car_wash->id],'class'=>'form-horizontal', 'files' => true, 'method' => 'patch']) }}
@else

    {!!  Form::open(array('route' =>'car_wash.store','class'=>'form-horizontal','files' => true )) !!}

@endif --}}

        <form action="/admin/book_car_wash" method="POST" class="form-horizontal" >
            {{ csrf_field() }}
            <div class="form-group">
            {!! Form::label('title','User Name :',['class'=>'col-sm-3 control-label'])!!}
            <div class="col-sm-6">
                {{ Form::select('user_id', 
                                $users,Input::old('user_id'),['class'=>'form-control'] ) }}
            </div>
        </div>
        <div class="form-group">
            {!! Form::label('title','First Name :',['class'=>'col-sm-3 control-label'])!!}
            <div class="col-sm-6">
                {!! Form::text('firstname',Input::old('firstname'),['class'=>'form-control'])!!}
            </div>
        </div>

        <div class="form-group">
        	{!! Form::label('title','Last Name :',['class'=>'col-sm-3 control-label'])!!}
            <div class="col-sm-6">
                {!! Form::text('lastname',Input::old('lastname'),['class'=>'form-control'])!!}
            </div>
        </div>

        <div class="form-group">
            {!! Form::label('title','Email :',['class'=>'col-sm-3 control-label'])!!}
            <div class="col-sm-6">
                {!! Form::text('email',Input::old('email'),['class'=>'form-control'])!!}
            </div>
        </div>
        
        <div class="form-group">
            {!! Form::label('title','Mobile :',['class'=>'col-sm-3 control-label'])!!}
            <div class="col-sm-6">
                {!! Form::text('mobile',Input::old('mobile'),['class'=>'form-control'])!!}
            </div>
        </div>

        <div class="form-group">
            {!! Form::label('title','Package Name :',['class'=>'col-sm-3 control-label'])!!}
            <div class="col-sm-6">
                {{ Form::select('package_id', 
                                $packages,Input::old('package_id'),['class'=>'form-control'] ) }}
            </div>
        </div>
        

        <div class="form-group">
            {!! Form::label('title','Brand Name :',['class'=>'col-sm-3 control-label'])!!}
            <div class="col-sm-6">
                {{ Form::select('brand_id', 
                                $brands,Input::old('brand_id'),['class'=>'form-control'] ) }}
            </div>
        </div>

        <div class="form-group">
            {!! Form::label('title','Model Name :',['class'=>'col-sm-3 control-label'])!!}
            <div class="col-sm-6">
                {{ Form::select('model_id', 
                                $carmodels,Input::old('model_id'),['class'=>'form-control'] ) }}
            </div>
        </div>

        <div class="form-group">
            {!! Form::label('title','Car Category :',['class'=>'col-sm-3 control-label'])!!}
            <div class="col-sm-6">
                {{ Form::select('car_type', 
                                [ 'hatchback' => 'Hatchback', 
                                  'sedan' => 'Sedan',
                                  'suv' => 'Suv',
                                  'compact suv' => 'Compact Suv',
                                  'premium' => 'Premium',
                                  'other' => 'Other'
                                ],Input::old('car_type'),['class'=>'form-control'] ) }}
            </div>
        </div>

        
        
       {{--  <div class="form-group">
            {!! Form::label('title','Package Image :',['class'=>'col-sm-3 control-label'])!!}
            <div class="col-sm-6">
                {!! Form::file('package_img',Input::old('brand_img'),['class'=>'form-control'])!!}
            </div>
        </div>	 --}}
       
        <div class="form-group">
            <div class="col-sm-6 col-sm-offset-5">
                {!! Form::submit('submit',array('class' => 'btn btn-primary'))!!}
            </div>
        </div>


    {!! Form::close() !!}                  
                        


                        


                        

                    
@endsection

resources/views/admin/add_car_wash.blade.php
@extends('layouts.admin')


@section('content')
<h4 class="header-title m-t-0 m-b-30">Default Example</h4>
<h4 class="header-title m-t-0 m-b-30">Add Car Wash Package </h4>
@if(isset($success))
    <div class="alert alert-success"> {{$success}} </div>
@endif
@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif     
       @if(isset($car_wash))
    {{ Form::model($car_wash, ['route' => ['car_wash.update', $car_wash->id],'class'=>'form-horizontal', 'files' => true, 'method' => 'patch']) }}
@else

    {!!  Form::open(array('route' =>'car_wash.store','class'=>'form-horizontal','files' => true )) !!}

@endif



        <div class="form-group">
            {!! Form::label('title','Package Name :',['class'=>'col-sm-3 control-label'])!!}
            <div class="col-sm-6">
                {!! Form::text('package_name',Input::old('package_name'),['class'=>'form-control'])!!}
            </div>
        </div>
        <div class="form-group">
            {!! Form::label('title','Package Category :',['class'=>'col-sm-3 control-label'])!!}
            <div class="col-sm-6">
                {{ Form::select('package_category', 
                				[ 'hatchback' => 'Hatchback', 
                				  'sedan' => 'Sedan',
                                  'suv' => 'Suv',
                                  'compact suv' => 'Compact Suv',
                                  'premium' => 'Premium',
                                  'other' => 'Other'
                				],Input::old('package_category'),['class'=>'form-control'] ) }}
            </div>
        </div>
        <div class="form-group">
            {!! Form::label('title','Package Type :',['class'=>'col-sm-3 control-label'])!!}
            <div class="col-sm-6">
                {{ Form::select('package_type', 
                				[ 
                				  'monthly' => 'Monthly',
                				  'quarterly' => 'Quarterly',
                				  'halfyearly' => 'Half-Yearly',
                				  'yearly' => 'Yearly'
                				],Input::old('package_type'),['class'=>'form-control'] ) }}
            </div>
        </div>
        <div class="form-group">
            {!! Form::label('title','Package Amount :',['class'=>'col-sm-3 control-label'])!!}
            <div class="col-sm-6">
                {!! Form::text('package_price',Input::old('package_price'),['class'=>'form-control'])!!}
            </div>
        </div>
        <div class="form-group">
        	{{-- <label for="" class="col-sm-3 control-label">Description</label>
        	<div class="col-sm-6">
        		
			<textarea class="ckeditor" name="package_desc">{{ Input::old('package_desc') }}</textarea>
        	</div> --}}
            {!! Form::label('title','Description :',['class'=>'col-sm-3 control-label'])!!}
            <div class="col-sm-6">
                {!! Form::textarea('package_desc',Input::old('package_desc'),['class'=>'ckeditor'])!!}
            </div>
        </div>
        
       {{--  <div class="form-group">
            {!! Form::label('title','Package Image :',['class'=>'col-sm-3 control-label'])!!}
            <div class="col-sm-6">
                {!! Form::file('package_img',Input::old('brand_img'),['class'=>'form-control'])!!}
            </div>
        </div>	 --}}
       
        <div class="form-group">
            <div class="col-sm-6 col-sm-offset-5">
                {!! Form::submit('submit',array('class' => 'btn btn-primary'))!!}
            </div>
        </div>


    {!! Form::close() !!}                  
                        


                        


                        

                    
@endsection

resources/views/admin/add_feedback.blade.php
@extends('layouts.admin')


@section('content')
<h4 class="header-title m-t-0 m-b-30">Default Example</h4>
<h4 class="header-title m-t-0 m-b-30">Add Feedback</h4>
@if(isset($success))
    <div class="alert alert-success"> {{$success}} </div>
@endif
@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
@if(isset($feedback))
    {{ Form::model($feedback, ['route' => ['feedbacks.update', $feedback->id],'class'=>'form-horizontal', 'files' => true, 'method' => 'patch']) }}
@else

    {!!  Form::open(array('route' =>'feedbacks.store','class'=>'form-horizontal','files' => true )) !!}

@endif
                                        
                                        
                <div class="form-group">
                    {!! Form::label('title','Name :',['class'=>'col-sm-3 control-label'])!!}
                    <div class="col-sm-6">
                        {!! Form::text('name',Input::old('name'),['class'=>'form-control'])!!}
                    </div>
                </div>
                <div class="form-group">
                    {!! Form::label('title','Description :',['class'=>'col-sm-3 control-label'])!!}
                    <div class="col-sm-6">
                        {!! Form::text('desc',Input::old('desc'),['class'=>'form-control'])!!}
                    </div>
                </div>
                
                <div class="form-group">
                    {!! Form::label('title','Image :',['class'=>'col-sm-3 control-label'])!!}
                    <div class="col-sm-6">
                        {!! Form::file('pic',Input::old('pic'),['class'=>'form-control'])!!}
                    </div>
                </div>	
               
                <div class="form-group">
                    <div class="col-sm-6 col-sm-offset-5">
                        {!! Form::submit('submit',array('class' => 'btn btn-primary'))!!}
                    </div>
                </div>


            {!! Form::close() !!}                  
                                         


                        

                    
@endsection

resources/views/admin/callbacks.blade.php
@extends('layouts.admin')


@section('content')
<h4 class="header-title m-t-0 m-b-30">Default Example</h4>
<h4 class="header-title m-t-0 m-b-30">Callbacks List</h4>
@if(Session::has('message'))
   <div class="alert alert-success">{{ Session::get('message') }}</div>
@endif
<table id="datatable" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Email</th>
            <th>Mobile</th>
            <th>Message</th>
            <th>Date</th>
            <th>Action</th>
        </tr>
    </thead>

    <tbody>
        <?php $i=1; ?>
        @foreach ($callbacks as $data)
        <tr>
            <td>{{ $i }}</td>
            <td>{{ $data->name }}</td>
            <td>{{ $data->email }}</td>
            <td>{{ $data->phone }}</td>
            <td>{{ $data->message }}</td>
            <td>{{ $data->created_at }}</td>
            <td>
                {{-- {{ link_to_route('data.edit','Edit',[$data->id], ['class'=> 'btn btn-primary btn-xs']) }} --}}

                    {{-- {!! Form::open(['method'=>'delete','route'=>['complain_destroy', $data->id]]) !!} --}}

                {{-- {!! Form::submit('Delete',['class'=>'btn btn-danger btn-xs' ])!!} --}}
           </td>
        </tr>
        <?php $i++; ?>
        @endforeach
       
    </tbody>
</table>                    
@endsection

resources/views/admin/complains.blade.php
@extends('layouts.admin')


@section('content')
<h4 class="header-title m-t-0 m-b-30">Default Example</h4>
<h4 class="header-title m-t-0 m-b-30">Complains List</h4>
@if(Session::has('message'))
   <div class="alert alert-success">{{ Session::get('message') }}</div>
@endif
<table id="datatable" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Email</th>
            <th>Mobile</th>
            <th>Message</th>
            <th>Date</th>
            <th>Action</th>
        </tr>
    </thead>

    <tbody>
        <?php $i=1; ?>
    	@foreach ($complains as $data)
        <tr>
            <td>{{ $i }}</td>
            <td>{{ $data->name }}</td>
            <td>{{ $data->email }}</td>
            <td>{{ $data->phone }}</td>
            <td>{{ $data->message }}</td>
            <td>{{ $data->created_at }}</td>
            <td>
                {{-- {{ link_to_route('data.edit','Edit',[$data->id], ['class'=> 'btn btn-primary btn-xs']) }} --}}

                    {{-- {!! Form::open(['method'=>'delete','route'=>['complain_destroy', $data->id]]) !!} --}}

                {{-- {!! Form::submit('Delete',['class'=>'btn btn-danger btn-xs' ])!!} --}}
           </td>
        </tr>
        <?php $i++; ?>
        @endforeach
       
    </tbody>
</table>                    
@endsection

resources/views/admin/faqlist.blade.php
@extends('layouts.admin')


@section('content')
<h4 class="header-title m-t-0 m-b-30">Default Example</h4>
<h4 class="header-title m-t-0 m-b-30">FAQ List <a href="/admin/faqs/create" class="btn btn-primary">Add new</a></h4>
@if(Session::has('message'))
   <div class="alert alert-success">{{ Session::get('message') }}</div>
@endif
<table id="datatable" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Question</th>
            <th>Answer</th>
            
            <th>Action</th>
        </tr>
    </thead>

    <tbody>
    	@foreach ($data as $faq)
        <tr>
            <td>{{ $faq->question }}</td>
            <td>{{ $faq->answer }}</td>
            
            <td>
                {{ link_to_route('faqs.edit','Edit',[$faq->id], ['class'=> 'btn btn-primary btn-xs']) }}

                    {!! Form::open(['method'=>'delete','route'=>['faqs.destroy', $faq->id]]) !!}

                {!! Form::submit('Delete',['class'=>'btn btn-danger btn-xs' ])!!}
           </td>
        </tr>
        @endforeach
       
    </tbody>
</table>                    
@endsection

resources/views/admin/seo.blade.php
@extends('layouts.admin')


@section('content')
<h4 class="header-title m-t-0 m-b-30">Default Example</h4>
<h4 class="header-title m-t-0 m-b-30">Car List &nbsp; <a href="{{ url('admin/cars/create')}}" class="btn btn-primary btn-xs">Add Car</a></h4>
@if(Session::has('message'))
   <div class="alert alert-success">{{ Session::get('message') }}</div>
@endif
<table id="datatable" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>#</th>
            <th>Title</th>
            <th>Page Name</th>
            <th>Keywords</th>
            <th>Meta description</th>
            <th>Tags</th>
            <th>Action</th>
        </tr>
    </thead>

    <tbody>
        <?php $i=1; ?>
    	@foreach ($seo as $data)
        <tr>
            <td> {{ $i }}</td>
            <td>{{ $data->title }}</td>
            <td>{{ $data->page_name }}</td>
            <td>{{ $data->keywords }}</td>
            <td>{{ $data->meta_desc }}</td>
            <td>{{ $data->tags }}</td>
            <td>
                {{ link_to_route('seo.edit','Edit',[$data->id], ['class'=> 'btn btn-primary btn-xs col-md-4']) }}                
           </td>
        </tr>
        <?php $i++; ?> 
        @endforeach
       
    </tbody>
</table>                    
@endsection

resources/views/admin/vehicle.blade.php
@extends('layouts.admin')


@section('content')
<h4 class="header-title m-t-0 m-b-30">Default Example</h4>
<h4 class="header-title m-t-0 m-b-30">Promocode List</h4>
@if(Session::has('message'))
   <div class="alert alert-success">{{ Session::get('message') }}</div>
@endif
<table id="datatable" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>status</th>
            <th>promo_code</th>
            <th>usable</th>
            <th>amount</th>
            <th>promo_type</th>
            <th>usage_type</th>
            <th>user_id</th>
            <th>expiry_date date</th>
            <th>message</th>
            <th>Action</th>
        </tr>
    </thead>

    <tbody>
    	@foreach ($data as $promocode)
        <tr>
            <td>{{ $promocode->status }}</td>
            <td>{{ $promocode->promo_code }}</td>
            <td>{{ $promocode->usable }}</td>
            <td>{{ $promocode->amount }}</td>
            <td>{{ $promocode->promo_type }}</td>
            <td>{{ $promocode->usage_type }}</td>
            <td>{{ $promocode->user_id }}</td>
            <td>{{ $promocode->expiry_date }}</td>
            <td>{{ $promocode->message }}</td>
            <td>
                {{ link_to_route('promocode.edit','Edit',[$promocode->id], ['class'=> 'btn btn-primary btn-xs']) }}

                    {!! Form::open(['method'=>'delete','route'=>['promocode.destroy', $promocode->id]]) !!}

                {!! Form::submit('Delete',['class'=>'btn btn-danger btn-xs' ])!!}
           </td>
        </tr>
        @endforeach
       
    </tbody>
</table>                    
@endsection